;;;----------------------------------------------------------------------------------
;;; Generated by protoc-gen-clojure.  DO NOT EDIT
;;;
;;; GRPC br.com.service.example.client.Example Service Implementation
;;;----------------------------------------------------------------------------------
(ns br.com.service.example.client.Example.server
  (:require [br.com.service.example.client :refer :all]
))

;-----------------------------------------------------------------------------
; GRPC Example
;-----------------------------------------------------------------------------
(defprotocol Service
  (Authenticate [this param]))

(defn- Authenticate-dispatch
  [ctx request]
  (Authenticate ctx request))

(def ^:const rpc-metadata
  [{:pkg "br.com.service.example.client" :service "Example" :method "Authenticate" :method-fn Authenticate-dispatch :server-streaming false :client-streaming false :input pb->AuthRequest :output new-AuthResponse}])
